### PR TITLE
Added vc11 support and updated to latest version 1.0.1c

### PR DESCRIPTION
**Pull request by bherila**

### CODE REVIEW

**Comment by madewokherd** [comment]
You clearly did the merge wrong. It should have two parent commits.

**Comment by bherila** [comment]
The downloads folder in my fork has proof that it builds :-)

**Comment by bherila** [comment]
> You clearly did the merge wrong. It should have two parent commits.

Ah, I found this: https://github.com/coapp/coapp.org/wiki/Tarball-fork

Can you recommend a way to fix it or do I need to start over? If the latter, is the problem really that bad?

**Comment by madewokherd** [comment]
It's important that we have the original source code in the history so that we can get a diff of our changes from upstream, and so that further merges are easier. (Which also means the upstream branch has to be the same revision that master is based on, and the line-endings need to match. You should do a diff to make sure of that.)

It's not as important that the history is in the right order. In the past, I've had to fix things up by merging in the tarball snapshot after the fact, using e.g. "git merge --strategy=ours upstream". I'd prefer a clean history, of course, but merges can make it difficult to fix. In other cases "git rebase -i" is your friend, and in this case it may even be possible to use that to redo only your merge commit, but I don't know how feasible that is given your level of experience with git.

(By the way, in the future you should check whether the CoApp branch exists and is ahead of master, in which case you should base your changes on that. But that's easily fixed with another merge; it just makes for an ugly history.)

**Comment by virmitio** [comment]
As the intended changes appear sound, I've performed a rebase of bherila's commits and will be pushing the changes to their appropriate branches.  This should also maintain a proper history in this repository.

This being the case, I am going to close this pull request.

**Pull request closed without merging**
